[package]
name = "cmpdt"
description = "compare directory trees"
version = "0.1.0-rc1"
edition = "2021"
license = "Unlicense"


[dependencies]
sha2 = "0.10"
hex = "0.4"

[features]
default = []
unix = []
